# Generated by Django 3.0.4 on 2020-03-06 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('category_name', models.CharField(max_length=100)),
                ('category_description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('sub_name', models.CharField(max_length=100)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News.Category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('news_title', models.CharField(max_length=100)),
                ('news_content', models.TextField()),
                ('news_image', models.ImageField(upload_to='news')),
                ('news_author', models.CharField(max_length=100)),
                ('views_count', models.PositiveIntegerField(default='0')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News.Category')),
                ('SubCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News.SubCategory')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
