# Generated by Django 3.0.4 on 2020-03-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='views_count',
            field=models.PositiveIntegerField(default='1'),
        ),
    ]
