# Generated by Django 3.0.4 on 2020-03-20 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0004_auto_20200319_2150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='Comments',
            new_name='news',
        ),
    ]
